### ISSUE TITLE
Obfuscating (a little bit) email in issues

### ISSUE THREAD

**Issue by tadzik** [chilts/cil#1]
Hi,
First of all, thanks for this nice piece of code :)
My idea, is to mess with email addreses a bit. Presenting them in a form like "user at domain dot com" or just "user at domain.com" isn't really less readable than the standard form, yet it might save our spamfilters some work.

Kind regards,
Ted

**Comment by chilts** [comment]
Added as issue d3ac4078 in cil itself. Good idea.

Thanks for your kind comments :)

**Comment by chilts** [comment]
I need to understand what you mean by this. I firstly suspected that you wanted the emails to be presented as such, but what I think you mean is for them to be munged before being saved in the issue.

And therefore, if you do something like this, for the email to be munged before comparison:

 $ cil issue --assigned-to=someone@example.com

This would be converted to "someone at example dot com" before being checked against the AssignedTo fields.

Is that what you meant?

**Comment by tadzik** [comment]
Yeah, sounds good. My point is that I put my repo e.g. on github, cil issues included, and my email address is just plaitexted there being a food for spambots wandering around.

**Comment by tadzik** [comment]
Also, I personally use almost only cil add --mine, so that's where I'd like the address obfuscated. It's taken from git config, right?

**Comment by chilts** [comment]
Added ability to obfuscate issues. This can be set by using a .cil directive called 'MungeEmail', which can be set to 0 or 1. It defaults to 0.
