### ISSUE TITLE
cil from ubuntu apt

### ISSUE THREAD

**Issue by Br3nda** [chilts/cil#10]
after a cil add, i get this error:
write_file 'issues/i_a73d1795.cil' - sysopen: No such file or directory at /usr/share/perl5/CIL/Utils.pm line 124

version is
ii  cil                                  0.5.1-2                                    command line issue tracker

**Comment by Br3nda** [comment]
i hadn't done cil init.
maybe we can have a better error message here?

**Comment by chilts** [comment]
I don't think this is a problem anymore.
