### ISSUE TITLE
Please move away from deprecated Getopt::Mixed

### ISSUE THREAD

**Issue by xtaran** [chilts/cil#16]
[Getopt::Mixed is deprecated and considered obsolete for quite a while now](https://metacpan.org/pod/Getopt::Mixed#DESCRIPTION) since [Getopt::Long](https://metacpan.org/pod/Getopt::Long) (part of Perl's core since ages) gained the possibility to use short options many years ago, too.

[Debian thinks about removing its libgetopt-mixed-perl package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=555116#25) and to be able to do this, cil needs to be changed away from Getopt::Mixed first.

**Comment by chilts** [comment]
Happy to have cil drop out of Debian. It's pretty much unmaintained now and with very few users and/or interest so I'm not sure it's worthy of any kind of update.

Feel free to fork if needed. I'm also happy to merge a patch if one is created, though I'm not sure I can or even remember how to publish to CPAN anymore.
