### ISSUE TITLE
How about `cil help`?

### ISSUE THREAD

**Issue by tadzik** [chilts/cil#3]
Won't it be easier to type than cil --help? And more git like :} I tried to look at the code, yet there is some option parsing I don't understand :) How do you find this idea?

Regards

**Comment by chilts** [comment]
You can now type "cil help" as well as "cil --help" (closed by 58ddb9a788f8098a7479a1bea61fb07f175d388d)

**Comment by chilts** [comment]
You can now type either of the following:

 $ cil --help
 $ cil help

Thanks for your issue (sorry it took me so long to get to it).
