### ISSUE TITLE
How about an option to list the labels?

### ISSUE THREAD

**Issue by afita** [chilts/cil#4]
I was thinking it would be nice to have an option to list all the labels (or some of them - like the labels of the active issues, open issue, finished issues etc.). This would be very useful when working with lots of issues that can have many labels and you can't remember their names - so you can use them on new issues.

**Comment by chilts** [comment]
Sounds like a good idea. I'll have a crack at it tonight (just got into work, so it'll have to wait a short while).

Thanks for your feedback :)

**Comment by chilts** [comment]
Hi afita,

Where were you wanting to list the labels? Do you mean a separate command such as:

<pre>$ cil list-labels
Type-Enhancement
Type-Defect
Priority-High
Priority-Medium
Priority-Low
</pre>


In fact, list-labels would be able to filter much like 'summary' and 'list', so for example you could do:

<pre>$ cil list-labels --mine
$ cil list-labels --is-open
$ cil list-labels --is-closed
$ cil list-labels --created-by=someone@example.com
$ cil list-labels --label=Priority-Low # useless, but it would come for free :)
</pre>

How does that all sound?

**Comment by chilts** [comment]
Add list-labels command (closed by 556da2dc6d8d9c569cefd7698cab1e139b536af2)

**Comment by chilts** [comment]
Ok, I've added the list-labels command and it works as above. Let me know what you think.

**Comment by afita** [comment]
Thank you. I'll comment on this as soon as I figure out how get the source out of github for testing (I don't yet know how to use git).

**Comment by afita** [comment]
I managed to get the source (it was simpler than I thought: I haven't notice the download source button in the top right corner :D). Works great so far, thanks.

I am using Ubuntu, and besides the already installed dependencies of "cil 0.5.1-2" (Ubuntu 10.04) I had to install the following packages also: libfile-homedir-perl, git-core, libdate-simple-perl.

The documentation needs to be updated also.

**Comment by chilts** [comment]
Just updated the docs to show Date::Simple. The other ones you specify are already there.
