### ISSUE TITLE
How about a due date (or expire date) on an issue

### ISSUE THREAD

**Issue by afita** [chilts/cil#5]
I would find it very handy to have a due date (or expire date, whatever you want to call it) on an issue.

And I would also like to filter the issue list (and summary) to show the issues that are past due or expire date.

Thanks.

**Comment by chilts** [comment]
Have added the ability to have a DueDate field.

Leaving issue open since I need to work on what filters we need.

e.g. I'll figure out the best of these :)

<pre>$ cil summary --is-overdue
$ cil summary --due-date=&gt;2010-12-16
$ cil summary --due-date=&lt;2010-01-16
$ cil summary --due-date='1 week'
$ cil summary --due-date='2 months'
$ cil summary --due-date='this year'
</pre>


I don't think I'll do all of these, but it's a start.

**Comment by afita** [comment]
I also think that the DueDate field should appear in the output of the 'cil list' command.

**Comment by chilts** [comment]
It does show up if it's defined. If it's not defined, it doesn't show.

**Comment by afita** [comment]
I wasn't talking about 'cil show', but 'cil list'. I think that the due date should appear in the report generated by 'cil list'.

I have looked through the source and found in lib/CIL/Command/List.pm that for the list command you call display_issue_headers($issue). After that I looked in lib/CIL/Utils.pm and found that the display_issue_headers function doesn't display the DueDate.

**Comment by afita** [comment]
For the filters I think that there should also be an option to sort the results by the DueDate (something like: the oldest expired issue should appear first).

**Comment by chilts** [comment]
Now shows the DueDate for List commands. Sorry afita, thanks for the heads up.

Could you create a new issue for the ordering? I think that is something I could make generic and not specifically related to this. For example, I could make it order on Inserted, Updated, AssignedTo, DueDate and maybe some other things.

Thanks.

**Comment by afita** [comment]
I have created a new issue for the ordering.

**Comment by chilts** [comment]
Hmm, this is closed. Not quite done with the querying of the DueDate field, but I've done the ordering now, so that'll help ... see issue #6.
