### ISSUE TITLE
Please add an option to order the issues

### ISSUE THREAD

**Issue by afita** [chilts/cil#6]
Please add an option to order the issues when listing and summarizing.

The ordering could be done on Inserted, Updated, AssignedTOo, DueDate.

**Comment by chilts** [comment]
This is now done. You can order on any of the following fields:
- Summary
- Inserted
- Updated
- AssignedTo
- CreatedBy
- DueDate
- Status

e.g. cil list --order=DueDate

You can also do a --reverse (boolean flag).

e.g. cil list --order=DueDate --reverse
